version: '2'
services:
    web:
        container_name: slim-web
        image: slim-web
        build: ./web
        links:
            - php
        volumes_from:
            - php
        ports:
            - "80:80"
        network_mode: bridge
    php:
        container_name: slim-php
        image: slim-php
        build: ./php
        volumes:
            - ${APP_DIR}:/home/app:cached
        links:
            - dbserver
        network_mode: bridge
    dbserver:
        container_name: slim-dbserver
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
        volumes:
            - ${APP_DB}:/usr/share/elasticsearch/data
            - ./database/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        cap_add:
            - IPC_LOCK         
        network_mode: bridge
        ports:
          - 9200:9200